// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvj0Yj2_rx64GsFjmBxe9iMU6ZG8UA3kc',
    appId: '1:411388009687:web:30d1ff021538a605a4e492',
    messagingSenderId: '411388009687',
    projectId: 'discare-917f9',
    authDomain: 'discare-917f9.firebaseapp.com',
    storageBucket: 'discare-917f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Ysjl2xX_jJaSQ9tc4YC1mG5zEhJqZv8',
    appId: '1:411388009687:android:a9f0d949f4ba6a50a4e492',
    messagingSenderId: '411388009687',
    projectId: 'discare-917f9',
    storageBucket: 'discare-917f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8HVTvG-DP0coi1aWHM-shlulRjX2W6MU',
    appId: '1:411388009687:ios:12f446b4caaceb3ea4e492',
    messagingSenderId: '411388009687',
    projectId: 'discare-917f9',
    storageBucket: 'discare-917f9.firebasestorage.app',
    iosBundleId: 'com.example.miraNewproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfh8NQfOLHwQGPh3NhWiZKkPhJNywuwtc',
    appId: '1:478789765009:ios:7a43c9c5041da47c37bc30',
    messagingSenderId: '478789765009',
    projectId: 'discare-729a6',
    storageBucket: 'discare-729a6.firebasestorage.app',
    iosBundleId: 'com.example.miraNewproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBViwWiKVRcIJqRoUpdh3pb5f5_GcUCmdc',
    appId: '1:478789765009:web:bd491f199fcf6c9637bc30',
    messagingSenderId: '478789765009',
    projectId: 'discare-729a6',
    authDomain: 'discare-729a6.firebaseapp.com',
    storageBucket: 'discare-729a6.firebasestorage.app',
    measurementId: 'G-FQK4X7N0S6',
  );
}